In [4]:
import numpy as np

In [76]:
np.set_printoptions(suppress=True)

#### Problem 1: Write a function so that the columns of the output matrix are powers of the input vector. 
The order of the powers is determined by the increasing boolean argument. 
Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde.

In [63]:
def generate_vander_matrix(input_vec, num_columns=-1, increasing=False):
    num_rows = len(input_vec)
    if (num_columns == -1):
        num_columns = len(input_vec)
    vander_mat = np.zeros((num_rows, num_columns))
    if(increasing):
        row_index = 0
        for x in input_vec:
            for y in range(0, num_columns):
                vander_mat[row_index][y] = x**y
            row_index = row_index + 1
    else:
        row_index = 0
        for x in input_vec:
            col_index = 0
            for y in range((num_columns-1),-1,-1):
                vander_mat[row_index][col_index] = x**y
                col_index = col_index + 1
            row_index = row_index + 1
    return vander_mat

In [60]:
input_vec = np.random.randint(1,10,4)
input_vec

array([7, 4, 1, 2])

In [64]:
vander_mat1 = generate_vander_matrix(input_vec)
vander_mat1

array([[343.,  49.,   7.,   1.],
       [ 64.,  16.,   4.,   1.],
       [  1.,   1.,   1.,   1.],
       [  8.,   4.,   2.,   1.]])

In [65]:
vander_mat2 = generate_vander_matrix(input_vec, 3)
vander_mat2

array([[49.,  7.,  1.],
       [16.,  4.,  1.],
       [ 1.,  1.,  1.],
       [ 4.,  2.,  1.]])

In [77]:
vander_mat3 = generate_vander_matrix(input_vec, 5)
vander_mat3

array([[2401.,  343.,   49.,    7.,    1.],
       [ 256.,   64.,   16.,    4.,    1.],
       [   1.,    1.,    1.,    1.,    1.],
       [  16.,    8.,    4.,    2.,    1.]])

In [81]:
vander_mat4 = generate_vander_matrix(input_vec, 4, True)
vander_mat4

array([[  1.,   7.,  49., 343.],
       [  1.,   4.,  16.,  64.],
       [  1.,   1.,   1.,   1.],
       [  1.,   2.,   4.,   8.]])

In [83]:
vander_mat5 = generate_vander_matrix(input_vec, 3, True)
vander_mat5

array([[ 1.,  7., 49.],
       [ 1.,  4., 16.],
       [ 1.,  1.,  1.],
       [ 1.,  2.,  4.]])

In [84]:
vander_mat6 = generate_vander_matrix(input_vec, 6, True)
vander_mat6

array([[    1.,     7.,    49.,   343.,  2401., 16807.],
       [    1.,     4.,    16.,    64.,   256.,  1024.],
       [    1.,     1.,     1.,     1.,     1.,     1.],
       [    1.,     2.,     4.,     8.,    16.,    32.]])

#### Problem 2:
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below
i 1 2 3 4 5 6 7 8 9 10
===== == == == == == == == == == ==
Input 10 20 30 40 50 60 70 80 90 100
y1 25 = (10+20+30+40)/4
y2 35 = (20+30+40+50)/4
y3 45 = (30+40+50+60)/4
y4 55 = (40+50+60+70)/4
y5 65 = (50+60+70+80)/4
y6 75 = (60+70+80+90)/4
y7 85 = (70+80+90+100)/4
Thus, the moving average sequence has n-k+1=10-4+1=7 values.
Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [86]:
def generate_moving_averages(input_vec, window_size=-1):
    if(window_size <=0):
        return 'Please enter a positive window size'
    else:
        moving_avgs_list = []
        num_moving_ags = len(input_vec) - window_size + 1
        start_index = 0
        for x in range(num_moving_ags):
            moving_avgs_list.append((input_vec[start_index:(start_index+window_size)]).mean())
            start_index = start_index + 1
        return np.array(moving_avgs_list)

In [88]:
input_vec = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
window = 3

In [89]:
generate_moving_averages(input_vec)

'Please enter a positive window size'

In [91]:
mov_avgs_arr = generate_moving_averages(input_vec, 3)
mov_avgs_arr

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])

In [94]:
print('Number of elements in original array = ',len(input_vec))
print('Window size = ',window)
print('Expected Number of elements in moving avgs array = ',(len(input_vec)-window+1))
print('Actual Number of elements in moving avgs array = ',len(mov_avgs_arr))
print('Actual moving avgs array = ',mov_avgs_arr)

Number of elements in original array =  13
Window size =  3
Expected Number of elements in moving avgs array =  11
Actual Number of elements in moving avgs array =  11
Actual moving avgs array =  [  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]
